swagger: "2.0"
info: 
  version: "0.0.1"
  title: "Lambda Functions"
  description: "REST service to get results from a lambda function using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "REST Service for Lambda Functions using Swagger"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes: 
  - "http"
consumes: 
  - "application/json"
  - "application/xml"
produces: 
  - "application/json"
  - "application/xml"
paths: 
  /add:
    get: 
      description: "Returns addition result from the hosting server"
      operationId: "addNum"
      produces: 
        - "application/json"
      parameters:
      - name: number1
        in: query
        description: "Number 1"
        required: true
        type: integer
      - name: number2
        in: query
        description: "Number 2"
        required: true
        type: integer        
      responses: 
        "200":
          description: "Addition result"
          schema: 
            $ref: "#/definitions/ADD"
definitions:
  ADD:
    type: "object"
    required: 
      - "model"
    properties: 
      model:
        type: "string"

